# Generated by Django 4.1 on 2022-08-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_ticket_trip_remove_trip_seat_remove_trip_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='origin',
            new_name='source',
        ),
    ]
