# Generated by Django 4.1 on 2022-09-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_booking_booking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='business_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='agency_certificate/'),
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_person_ID',
            field=models.ImageField(blank=True, null=True, upload_to='user_ID/'),
        ),
        migrations.AddField(
            model_name='agency',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
