# Generated by Django 4.1 on 2022-08-27 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='logo',
        ),
    ]
