# Generated by Django 4.1 on 2022-08-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_agency_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_num',
            field=models.IntegerField(default=0),
        ),
    ]
