# Generated by Django 4.1 on 2022-09-02 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_ticket_booking_alter_ticket_ticket_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'permissions': [('cashout_from_wallet', 'Can cashout from wallet')]},
        ),
    ]
