# Generated by Django 4.1 on 2022-09-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_wallet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
